version: '1.0'
services:
  rela-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: rela-backend:latest
    container_name: rela-backend
    ports:
      - "4444:4444"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped
volumes:
  mongodb-data: